/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Sections = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & Cta)
>;

export type Cta = {
  _type: 'cta';
  overline?: string;
  title: BlockContent;
  description?: BlockContent;
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
  media?: {
    type: 'image' | 'video';
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    video?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
      };
      media?: unknown;
      _type: 'file';
    };
  };
  theme?: Theme;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?:
        | 'normal'
        | 'display1'
        | 'display2'
        | 'h1'
        | 'h2'
        | 'h3'
        | 'h4'
        | 'h5'
        | 'h6'
        | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      style?: 'line' | 'space';
      _type: 'separator';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Hero = {
  _type: 'hero';
  title: BlockContent;
  description?: BlockContent;
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
  media?: {
    type: 'image' | 'video';
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    video?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
      };
      media?: unknown;
      _type: 'file';
    };
  };
  theme?: Theme;
};

export type Seo = {
  _type: 'seo';
  title?: string;
  description?: string;
  keywords?: Array<string>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  ogTitle?: string;
  ogDescription?: string;
  noIndex?: boolean;
  canonicalUrl?: string;
};

export type Theme = {
  _type: 'theme';
  backgroundColor?: Color;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  backgroundVideo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    _type: 'file';
  };
  padding?: {
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
  };
  maxWidth?: 'full' | 'container' | 'small' | 'medium' | 'large';
};

export type ExternalLink = {
  _type: 'externalLink';
  url: string;
  title: string;
  openInNewTab?: boolean;
};

export type InternalLink = {
  _type: 'internalLink';
  reference: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  title?: string;
};

export type Link = {
  _type: 'link';
  linkType: 'internal' | 'external';
  variant?: 'solid' | 'outlined' | 'text';
  color?: 'primary' | 'secondary' | 'accent' | 'neutral';
  size?: 'small' | 'medium' | 'large';
  internalLink?: InternalLink;
  externalLink?: ExternalLink;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  seo?: Seo;
  theme?: Theme;
  sections?: Sections;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Home = {
  _id: string;
  _type: 'home';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  sections?: Sections;
  seo?: Seo;
  theme?: Theme;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Color = {
  _type: 'color';
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Footer = {
  _type: 'footer';
  links: Array<
    {
      _key: string;
    } & InternalLink
  >;
};

export type Header = {
  _type: 'header';
  links: Array<
    {
      _key: string;
    } & InternalLink
  >;
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: Header;
  footer?: Footer;
};

export type RgbaColor = {
  _type: 'rgbaColor';
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: 'hsvaColor';
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: 'hslaColor';
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Sections
  | Cta
  | BlockContent
  | Hero
  | Seo
  | Theme
  | ExternalLink
  | InternalLink
  | Link
  | Page
  | Slug
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | Color
  | Footer
  | Header
  | Settings
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0] {    header {      links[] { ..., }    },    footer {      links[] { ..., },      socialLinks[] { url, title, openInNewTab }    }  }
export type SETTINGS_QUERYResult = {
  header: {
    links: Array<{
      _key: string;
      _type: 'internalLink';
      reference: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'page';
      };
      title?: string;
    }>;
  } | null;
  footer: {
    links: Array<{
      _key: string;
      _type: 'internalLink';
      reference: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'page';
      };
      title?: string;
    }>;
    socialLinks: null;
  } | null;
} | null;
// Variable: refinedSectionsFragment
// Query: sections[]{  ...,  _type == "hero" => {    ...,    "media": {      ...media,      "image": media.image.asset->url    },    "ctas": ctas[]{      ...,      "href": select(        linkType == "external" => externalLink.url,        "/" + internalLink.reference->slug.current      ),      "label": select(        linkType == "external" => externalLink.title,        internalLink.title      )    }  },  _type == "cta" => {    ...,    "media": {      ...media,      "image": media.image.asset->url    },    "ctas": ctas[]{      ...,      "href": select(        linkType == "external" => externalLink.url,        "/" + internalLink.reference->slug.current      ),      "label": select(        linkType == "external" => externalLink.title,        internalLink.title      )    }  }}
export type RefinedSectionsFragmentResult = never;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    ...,    sections[]{  ...,  _type == "hero" => {    ...,    "media": {      ...media,      "image": media.image.asset->url    },    "ctas": ctas[]{      ...,      "href": select(        linkType == "external" => externalLink.url,        "/" + internalLink.reference->slug.current      ),      "label": select(        linkType == "external" => externalLink.title,        internalLink.title      )    }  },  _type == "cta" => {    ...,    "media": {      ...media,      "image": media.image.asset->url    },    "ctas": ctas[]{      ...,      "href": select(        linkType == "external" => externalLink.url,        "/" + internalLink.reference->slug.current      ),      "label": select(        linkType == "external" => externalLink.title,        internalLink.title      )    }  }}  }
export type PAGE_QUERYResult = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  seo?: Seo;
  theme?: Theme;
  sections: Array<
    | {
        _key: string;
        _type: 'cta';
        overline?: string;
        title: BlockContent;
        description?: BlockContent;
        ctas: Array<{
          _key: string;
          _type: 'link';
          linkType: 'external' | 'internal';
          variant?: 'outlined' | 'solid' | 'text';
          color?: 'accent' | 'neutral' | 'primary' | 'secondary';
          size?: 'large' | 'medium' | 'small';
          internalLink?: InternalLink;
          externalLink?: ExternalLink;
          href: string | null;
          label: string | null;
        }> | null;
        media:
          | {
              type: 'image' | 'video';
              image: string | null;
              video?: {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                };
                media?: unknown;
                _type: 'file';
              };
            }
          | {
              image: string | null;
            };
        theme?: Theme;
      }
    | {
        _key: string;
        _type: 'hero';
        title: BlockContent;
        description?: BlockContent;
        ctas: Array<{
          _key: string;
          _type: 'link';
          linkType: 'external' | 'internal';
          variant?: 'outlined' | 'solid' | 'text';
          color?: 'accent' | 'neutral' | 'primary' | 'secondary';
          size?: 'large' | 'medium' | 'small';
          internalLink?: InternalLink;
          externalLink?: ExternalLink;
          href: string | null;
          label: string | null;
        }> | null;
        media:
          | {
              type: 'image' | 'video';
              image: string | null;
              video?: {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                };
                media?: unknown;
                _type: 'file';
              };
            }
          | {
              image: string | null;
            };
        theme?: Theme;
      }
  > | null;
} | null;
// Variable: HOME_QUERY
// Query: *[_type == "home"][0] {    ...,    sections[]{  ...,  _type == "hero" => {    ...,    "media": {      ...media,      "image": media.image.asset->url    },    "ctas": ctas[]{      ...,      "href": select(        linkType == "external" => externalLink.url,        "/" + internalLink.reference->slug.current      ),      "label": select(        linkType == "external" => externalLink.title,        internalLink.title      )    }  },  _type == "cta" => {    ...,    "media": {      ...media,      "image": media.image.asset->url    },    "ctas": ctas[]{      ...,      "href": select(        linkType == "external" => externalLink.url,        "/" + internalLink.reference->slug.current      ),      "label": select(        linkType == "external" => externalLink.title,        internalLink.title      )    }  }}  }
export type HOME_QUERYResult = {
  _id: string;
  _type: 'home';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  sections: Array<
    | {
        _key: string;
        _type: 'cta';
        overline?: string;
        title: BlockContent;
        description?: BlockContent;
        ctas: Array<{
          _key: string;
          _type: 'link';
          linkType: 'external' | 'internal';
          variant?: 'outlined' | 'solid' | 'text';
          color?: 'accent' | 'neutral' | 'primary' | 'secondary';
          size?: 'large' | 'medium' | 'small';
          internalLink?: InternalLink;
          externalLink?: ExternalLink;
          href: string | null;
          label: string | null;
        }> | null;
        media:
          | {
              type: 'image' | 'video';
              image: string | null;
              video?: {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                };
                media?: unknown;
                _type: 'file';
              };
            }
          | {
              image: string | null;
            };
        theme?: Theme;
      }
    | {
        _key: string;
        _type: 'hero';
        title: BlockContent;
        description?: BlockContent;
        ctas: Array<{
          _key: string;
          _type: 'link';
          linkType: 'external' | 'internal';
          variant?: 'outlined' | 'solid' | 'text';
          color?: 'accent' | 'neutral' | 'primary' | 'secondary';
          size?: 'large' | 'medium' | 'small';
          internalLink?: InternalLink;
          externalLink?: ExternalLink;
          href: string | null;
          label: string | null;
        }> | null;
        media:
          | {
              type: 'image' | 'video';
              image: string | null;
              video?: {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                };
                media?: unknown;
                _type: 'file';
              };
            }
          | {
              image: string | null;
            };
        theme?: Theme;
      }
  > | null;
  seo?: Seo;
  theme?: Theme;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "settings"][0] {\n    header {\n      links[] { ..., }\n    },\n    footer {\n      links[] { ..., },\n      socialLinks[] { url, title, openInNewTab }\n    }\n  }\n': SETTINGS_QUERYResult;
    '\nsections[]{\n  ...,\n  _type == "hero" => {\n    ...,\n    "media": {\n      ...media,\n      "image": media.image.asset->url\n    },\n    "ctas": ctas[]{\n      ...,\n      "href": select(\n        linkType == "external" => externalLink.url,\n        "/" + internalLink.reference->slug.current\n      ),\n      "label": select(\n        linkType == "external" => externalLink.title,\n        internalLink.title\n      )\n    }\n  },\n  _type == "cta" => {\n    ...,\n    "media": {\n      ...media,\n      "image": media.image.asset->url\n    },\n    "ctas": ctas[]{\n      ...,\n      "href": select(\n        linkType == "external" => externalLink.url,\n        "/" + internalLink.reference->slug.current\n      ),\n      "label": select(\n        linkType == "external" => externalLink.title,\n        internalLink.title\n      )\n    }\n  }\n}': RefinedSectionsFragmentResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    ...,\n    \nsections[]{\n  ...,\n  _type == "hero" => {\n    ...,\n    "media": {\n      ...media,\n      "image": media.image.asset->url\n    },\n    "ctas": ctas[]{\n      ...,\n      "href": select(\n        linkType == "external" => externalLink.url,\n        "/" + internalLink.reference->slug.current\n      ),\n      "label": select(\n        linkType == "external" => externalLink.title,\n        internalLink.title\n      )\n    }\n  },\n  _type == "cta" => {\n    ...,\n    "media": {\n      ...media,\n      "image": media.image.asset->url\n    },\n    "ctas": ctas[]{\n      ...,\n      "href": select(\n        linkType == "external" => externalLink.url,\n        "/" + internalLink.reference->slug.current\n      ),\n      "label": select(\n        linkType == "external" => externalLink.title,\n        internalLink.title\n      )\n    }\n  }\n}\n  }\n': PAGE_QUERYResult;
    '\n  *[_type == "home"][0] {\n    ...,\n    \nsections[]{\n  ...,\n  _type == "hero" => {\n    ...,\n    "media": {\n      ...media,\n      "image": media.image.asset->url\n    },\n    "ctas": ctas[]{\n      ...,\n      "href": select(\n        linkType == "external" => externalLink.url,\n        "/" + internalLink.reference->slug.current\n      ),\n      "label": select(\n        linkType == "external" => externalLink.title,\n        internalLink.title\n      )\n    }\n  },\n  _type == "cta" => {\n    ...,\n    "media": {\n      ...media,\n      "image": media.image.asset->url\n    },\n    "ctas": ctas[]{\n      ...,\n      "href": select(\n        linkType == "external" => externalLink.url,\n        "/" + internalLink.reference->slug.current\n      ),\n      "label": select(\n        linkType == "external" => externalLink.title,\n        internalLink.title\n      )\n    }\n  }\n}\n  }\n': HOME_QUERYResult;
  }
}
